<a href="https://colab.research.google.com/github/RajeshRanaGiet/AML-LAB/blob/main/Experiment%206/AML_EXP_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
alpha = float(input("Enter the chi square tabulated : "))
m = int(input("Enter the number of rows : "))
matrix = []
print("Enter the data :- ")
for i in range(m):
  temp = [int(x) for x in input(f"Enter for {i+1} rows :- ").split(",")]
  temp.append(sum(temp))
  matrix.append(temp)
matrix.append(np.sum(matrix, axis = 0))
matrix = np.array(matrix)
print(matrix)
n = len(matrix[0])-1
#caluclating the expected value



Enter the chi square tabulated : 3.481
Enter the number of rows : 2
Enter the data :- 
Enter for 1 rows :- 10,5
Enter for 2 rows :- 5,10
[[10  5 15]
 [ 5 10 15]
 [15 15 30]]


In [ ]:
tempMatrix = []
tempChi = []
for i in range(m):
  temp1 = []
  for j in range(n):
    temp2 = (matrix[i][-1]*matrix[m][j])/matrix[m][n]
    temp1.append(temp2)
    tempChi.append((temp2-matrix[i][j])**2/temp2)
  tempMatrix.append(temp1)
print("The expected value is :\n",np.array(tempMatrix))
print("The calculated chi square value is :- ", sum(tempChi))
if sum(tempChi) < alpha:
  print("The null hypothesis is accepted")
else:
  print("The null hypothesis is rejected")

The expected value is :
 [[7.5 7.5]
 [7.5 7.5]]
The calculated chi square value is :-  3.3333333333333335
The null hypothesis is rejected


In [8]:
tabulated_val = float(input("Enter the tabulated Chi-Square value (critical value): "))
m = int(input("Enter number of rows: "))
print("Enter data for each row :")
observed = []
for i in range(m):
    row = [float(x) for x in input(f"Row {i+1}: ").replace(',', ' ').split()]
    observed.append(row)
rows = len(observed)
cols = len(observed[0])
row_totals = [sum(row) for row in observed]
col_totals = [sum(observed[r][c] for r in range(rows)) for c in range(cols)]
grand_total = sum(row_totals)
print("\n" + "=" * 55)
print("Row\tCol\tObserved (O)\tExpected (E)\t(O-E)^2/E")
print("=" * 55)
chi_square_stat = 0
for r in range(rows):
    for c in range(cols):
        o_val = observed[r][c]
        e_val = (row_totals[r] * col_totals[c]) / grand_total
        cell_chi = ((o_val - e_val) ** 2) / e_val
        chi_square_stat += cell_chi
        print(f"{r+1}\t{c+1}\t{o_val:.2f}\t\t{e_val:.4f}\t\t{cell_chi:.4f}")
print("=" * 55)
dof = (rows - 1) * (cols - 1)
print("\n--- Summary ---")
print(f"Degrees of Freedom (dof)   : {dof}")
print(f"Calculated Chi-Square Value: {chi_square_stat:.4f}")
print(f"Tabulated Chi-Square Value : {tabulated_val:.4f}")

if chi_square_stat < tabulated_val:
    print("\nDecision: Accept the Null Hypothesis (H0)")
else:
    print("\nDecision: Reject the Null Hypothesis (H0)")

Enter the tabulated Chi-Square value (critical value): 3.841
Enter number of rows: 2
Enter data for each row :
Row 1: 10,5
Row 2: 5,10

Row	Col	Observed (O)	Expected (E)	(O-E)^2/E
1	1	10.00		7.5000		0.8333
1	2	5.00		7.5000		0.8333
2	1	5.00		7.5000		0.8333
2	2	10.00		7.5000		0.8333

--- Summary ---
Degrees of Freedom (dof)   : 1
Calculated Chi-Square Value: 3.3333
Tabulated Chi-Square Value : 3.8410

Decision: Accept the Null Hypothesis (H0)
